name: daviscru
dependencies:
  redstone: any
  shelf_static: any
  google_oauth2_client: '>=0.3.4'
  google_plus_v1_api: any
  browser: any
  angular: any
  shadow_dom: any
  route_hierarchical: any
transformers:
- angular