name: daviscru
version: 0.0.1
dependencies:
  redstone: any
  redstone_mapper_mongo: any
  shelf_static: any
  dart_config: any
  http: any
  crypto: any

  google_oauth2_client: any
  google_plus_v1_api: any
  browser: any
  angular: any
  route_hierarchical: any
dependency_overrides:
  route_hierarchical:
    git:
      url: git://github.com/dgresham/route.dart.git
      ref: route-with-slashes
transformers:
- angular