name: daviscru
version: 0.0.1
dependencies:
  redstone: ">=0.5.4 <0.6.0"
  shelf_static: ">=0.1.4+6 <0.2.0"
  google_oauth2_client: ">=0.3.9 <0.4.0"
  google_plus_v1_api: ">=0.4.14 <0.5.0"
  browser: ">=0.10.0+2 <0.11.0"
  angular: ">=0.12.0 <0.13.0"
  route_hierarchical: ">=0.4.21 <0.5.0"
transformers:
- angular